name: Test

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  main:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        # Test non-EOL versions:
        node-version: [22, 24, 26]
        # Also test the oldest version we support:
        include:
          - os: ubuntu-latest
            node-version: 12
          # Node.js 12 isn’t supported on the macOS arm64 runners, only Intel.
          # It’s good to have a macOS Intel test, too.
          - os: macOS-26-intel
            node-version: 12
          - os: windows-latest
            node-version: 12

    env:
      ELM_HOME: '${{ github.workspace }}/elm-stuff/elm-home'

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v6
        with:
          node-version: '${{ matrix.node-version }}'

      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v6
        with:
          path: node_modules
          key: node_modules-${{ matrix.os }}-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}

      - name: Cache ELM_HOME
        uses: actions/cache@v6
        with:
          path: '${{ env.ELM_HOME }}'
          key: elm-${{ matrix.os }}-${{ hashFiles('elm-tooling.json', 'elm/**/elm.json', 'example-*/**/elm.json', 'tests/**/elm.json') }}

      - name: npm ci
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm ci --no-audit
        env:
          NO_ELM_TOOLING_INSTALL: 1

      - name: install mocha 9
        if: steps.cache-node_modules.outputs.cache-hit != 'true' && matrix.node-version == '12'
        run: npm install mocha@9

      - name: elm-tooling install
        run: npx elm-tooling install

      - name: Mocha
        run: npx mocha tests

      - name: elm-test
        run: npm run elm-test
